    version: 0.2

    phases:
      install:
        runtime-versions:
          # Specify runtime if needed, e.g., python: 3.9
      pre_build:
        commands:
          # Any commands to prepare your files before zipping
      build:
        commands:
          - echo "Uploading files to S3..."
          - aws s3 sync . s3://prodyot-demo-cloudfront --delete
          - echo "Upload complete."
    artifacts:
      files:
        - '**/*'
